In [1]:
!python -m pip install pandas sentence-transformers faiss-cpu

Requirement already satisfied: pandas in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (2.3.3)
Requirement already satisfied: sentence-transformers in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (5.2.3)
Requirement already satisfied: faiss-cpu in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (1.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: numpy>=1.22.4 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: scikit-learn in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from sentence-transformers) (1.7.2)
Requirement already satisfied: torch>=1.11.0 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from sentence-transformers) (2.10.0)
Requirement already satisfied: typing_extensions>=4.5.0 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: huggingface-hub>=0.20.0 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from sentence-transformers) (1.5.0)
Requirement already satisfied: tqdm in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: scipy in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from sentence-transformers) (1.15.3)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from sentence-transformers) (5.3.0)
Requirement already satisfied: packaging in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from faiss-cpu) (26.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.3.2)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2026.2.0)
Requirement already satisfied: filelock>=3.10.0 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.25.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.28.1)
Requirement already satisfied: typer in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.24.1)
Requirement already satisfied: pyyaml>=5.1 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.3)
Requirement already satisfied: six>=1.5 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: jinja2 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: networkx>=2.5.1 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.4.2)
Requirement already satisfied: colorama in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from tqdm->sentence-transformers) (0.4.6)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: regex!=2019.12.17 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2026.2.28)
Requirement already satisfied: joblib>=1.2.0 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: anyio in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (4.12.1)
Requirement already satisfied: idna in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (3.11)
Requirement already satisfied: httpcore==1.* in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (1.0.9)
Requirement already satisfied: certifi in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (2026.2.25)
Requirement already satisfied: h11>=0.16 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (0.0.4)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (1.5.4)
Requirement already satisfied: click>=8.2.1 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (8.3.1)
Requirement already satisfied: rich>=12.3.0 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (14.3.3)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (2.19.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (4.0.0)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (1.3.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (0.1.2)

[notice] A new release of pip available: 22.2.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
from sentence_transformers import SentenceTransformer
import faiss
import numpy as np

C:\Users\Valentina J K\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
data = {
    "title": [
        "Circe",
        "Atomic Habits",
        "Harry Potter",
        "The Poppy War",
        "The Alchemist",
        "Dune",
        "The Night Circus",
        "Educated",
        "The Hobbit",
        "Thinking Fast and Slow"
    ],
    
    "genre": [
        "Fantasy",
        "Self Help",
        "Fantasy",
        "Fantasy",
        "Fiction",
        "Science Fiction",
        "Fantasy",
        "Memoir",
        "Fantasy",
        "Psychology"
    ],
    
    "description": [
        "Greek mythological story of a powerful witch",
        "Guide to building good habits and breaking bad ones",
        "A young wizard discovering magic",
        "War and magic story with a powerful heroine",
        "A shepherd searching for treasure and meaning",
        "Political conflict on a desert planet",
        "A magical competition between illusionists",
        "A woman escaping a survivalist family",
        "A hobbit going on an unexpected adventure",
        "Explains how humans think and make decisions"
    ]
}

df = pd.DataFrame(data)

df

,title,genre,description
0,Circe,Fantasy,Greek mythological story of a powerful witch
1,Atomic Habits,Self Help,Guide to building good habits and breaking bad...
2,Harry Potter,Fantasy,A young wizard discovering magic
3,The Poppy War,Fantasy,War and magic story with a powerful heroine
4,The Alchemist,Fiction,A shepherd searching for treasure and meaning
5,Dune,Science Fiction,Political conflict on a desert planet
6,The Night Circus,Fantasy,A magical competition between illusionists
7,Educated,Memoir,A woman escaping a survivalist family
8,The Hobbit,Fantasy,A hobbit going on an unexpected adventure
9,Thinking Fast and Slow,Psychology,Explains how humans think and make decisions

In [4]:
import pandas as pd

data = {
    "title": [
        "Circe",
        "Atomic Habits",
        "Harry Potter",
        "The Poppy War",
        "The Alchemist",
        "Dune",
        "The Night Circus",
        "Educated",
        "The Hobbit",
        "Thinking Fast and Slow"
    ],
    
    "genre": [
        "Fantasy",
        "Self Help",
        "Fantasy",
        "Fantasy",
        "Fiction",
        "Science Fiction",
        "Fantasy",
        "Memoir",
        "Fantasy",
        "Psychology"
    ],
    
    "description": [
        "Greek mythological story of a powerful witch",
        "Guide to building good habits and breaking bad ones",
        "A young wizard discovering magic",
        "War and magic story with a powerful heroine",
        "A shepherd searching for treasure and meaning",
        "Political conflict on a desert planet",
        "A magical competition between illusionists",
        "A woman escaping a survivalist family",
        "A hobbit going on an unexpected adventure",
        "Explains how humans think and make decisions"
    ]
}

df = pd.DataFrame(data)

print(df)

                    title            genre  \
0                   Circe          Fantasy
1           Atomic Habits        Self Help
2            Harry Potter          Fantasy
3           The Poppy War          Fantasy
4           The Alchemist          Fiction
5                    Dune  Science Fiction
6        The Night Circus          Fantasy
7                Educated           Memoir
8              The Hobbit          Fantasy
9  Thinking Fast and Slow       Psychology

                                         description
0       Greek mythological story of a powerful witch
1  Guide to building good habits and breaking bad...
2                   A young wizard discovering magic
3        War and magic story with a powerful heroine
4      A shepherd searching for treasure and meaning
5              Political conflict on a desert planet
6         A magical competition between illusionists
7              A woman escaping a survivalist family
8          A hobbit going on an unexpected adventure
9       Explains how humans think and make decisions

In [5]:
df["combined_text"] = df["title"] + " " + df["genre"] + " " + df["description"]

df[["title","combined_text"]]

                    title                                      combined_text
0                   Circe  Circe Fantasy Greek mythological story of a po...
1           Atomic Habits  Atomic Habits Self Help Guide to building good...
2            Harry Potter  Harry Potter Fantasy A young wizard discoverin...
3           The Poppy War  The Poppy War Fantasy War and magic story with...
4           The Alchemist  The Alchemist Fiction A shepherd searching for...
5                    Dune  Dune Science Fiction Political conflict on a d...
6        The Night Circus  The Night Circus Fantasy A magical competition...
7                Educated  Educated Memoir A woman escaping a survivalist...
8              The Hobbit  The Hobbit Fantasy A hobbit going on an unexpe...
9  Thinking Fast and Slow  Thinking Fast and Slow Psychology Explains how...

In [6]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('all-MiniLM-L6-v2')

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|█████████████████████████████████| 103/103 [00:00<00:00, 4265.32it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [7]:
embeddings = model.encode(df["combined_text"].tolist())

print(embeddings.shape)

(10, 384)

In [8]:
import faiss
import numpy as np

dimension = embeddings.shape[1]

index = faiss.IndexFlatL2(dimension)
index.add(np.array(embeddings))

print("Vector database created!")

Vector database created!

In [9]:
def recommend_books(query, top_k=5):
    
    # convert query to embedding
    query_vector = model.encode([query])
    
    # search the vector database
    distances, indices = index.search(np.array(query_vector), top_k)
    
    # get recommended books
    results = df.iloc[indices[0]][["title","genre"]]
    
    return results

In [10]:
recommend_books("dark fantasy magic")

              title    genre
2      Harry Potter  Fantasy
6  The Night Circus  Fantasy
3     The Poppy War  Fantasy
0             Circe  Fantasy
8        The Hobbit  Fantasy

In [11]:
recommend_books("wizard magic school")

              title    genre
2      Harry Potter  Fantasy
6  The Night Circus  Fantasy
3     The Poppy War  Fantasy
0             Circe  Fantasy
8        The Hobbit  Fantasy

In [12]:
recommend_books("space politics desert")

              title            genre
5              Dune  Science Fiction
6  The Night Circus          Fantasy
3     The Poppy War          Fantasy
7          Educated           Memoir
8        The Hobbit          Fantasy

In [13]:
recommend_books("self improvement habits")

                    title       genre
1           Atomic Habits   Self Help
9  Thinking Fast and Slow  Psychology
2            Harry Potter     Fantasy
6        The Night Circus     Fantasy
4           The Alchemist     Fiction

In [14]:
def retrieve_context(query, top_k=3):
    
    query_vector = model.encode([query])
    
    distances, indices = index.search(np.array(query_vector), top_k)
    
    results = df.iloc[indices[0]]
    
    context = ""
    
    for _, row in results.iterrows():
        context += f"Book: {row['title']}\nGenre: {row['genre']}\nDescription: {row['description']}\n\n"
    
    return context

In [15]:
print(retrieve_context("dark fantasy magic"))

Book: Harry Potter
Genre: Fantasy
Description: A young wizard discovering magic

Book: The Night Circus
Genre: Fantasy
Description: A magical competition between illusionists

Book: The Poppy War
Genre: Fantasy
Description: War and magic story with a powerful heroine

In [16]:
print(retrieve_context("magic wizard school"))

Book: Harry Potter
Genre: Fantasy
Description: A young wizard discovering magic

Book: The Night Circus
Genre: Fantasy
Description: A magical competition between illusionists

Book: The Poppy War
Genre: Fantasy
Description: War and magic story with a powerful heroine

In [17]:
!python -m pip install transformers

Requirement already satisfied: transformers in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (5.3.0)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from transformers) (0.7.0)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from transformers) (0.22.2)
Requirement already satisfied: tqdm>=4.27 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from transformers) (4.67.3)
Requirement already satisfied: packaging>=20.0 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from transformers) (26.0)
Requirement already satisfied: numpy>=1.17 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from transformers) (2.2.6)
Requirement already satisfied: typer in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from transformers) (0.24.1)
Requirement already satisfied: regex!=2019.12.17 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from transformers) (2026.2.28)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from transformers) (1.5.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from transformers) (6.0.3)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (2026.2.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.3.2)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (4.15.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: filelock>=3.10.0 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (3.25.0)
Requirement already satisfied: colorama in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: rich>=12.3.0 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from typer->transformers) (14.3.3)
Requirement already satisfied: click>=8.2.1 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from typer->transformers) (8.3.1)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: idna in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (3.11)
Requirement already satisfied: anyio in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.12.1)
Requirement already satisfied: certifi in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from rich>=12.3.0->typer->transformers) (2.19.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from rich>=12.3.0->typer->transformers) (4.0.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers) (0.1.2)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\valentina j k\appdata\local\programs\python\python310\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.3.1)

[notice] A new release of pip available: 22.2.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [18]:
from transformers import pipeline

generator = pipeline("text-generation", model="gpt2")

Loading weights: 100%|█████████████████████████████████| 148/148 [00:00<00:00, 3069.51it/s]

In [19]:
def ask_sherlock(query):
    
    context = retrieve_context(query)
    
    prompt = f"""
You are an intelligent book recommendation assistant.

User query: {query}

Relevant books:
{context}

Explain why these books may be good recommendations.
"""
    
    response = generator(prompt, max_length=200, num_return_sequences=1)
    
    return response[0]['generated_text']

In [20]:
print(ask_sherlock("dark fantasy magic"))

Passing `generation_config` together with generation-related arguments=({'max_length', 'num_return_sequences'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Both `max_new_tokens` (=256) and `max_length`(=200) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

You are an intelligent book recommendation assistant.

User query: dark fantasy magic

Relevant books:
Book: Harry Potter
Genre: Fantasy
Description: A young wizard discovering magic

Book: The Night Circus
Genre: Fantasy
Description: A magical competition between illusionists

Book: The Poppy War
Genre: Fantasy
Description: War and magic story with a powerful heroine



Explain why these books may be good recommendations.

User query: books of the good old days

Relevant books:

Book: The Lost World of Harry Potter

Genre: English

Description: A family drama with two adults

Book: The Ravenclaw Temple

Genre: English

Description: A magical ritual involving wizards and witches

Book: The Secret of the Dark Tower

Genre: English

Description: A magical journey through time

Book: The Dark Lord's Curse

Genre: English

Description: A journey through the Middle Ages to the end of time


Book: A Story of the Witches

Genre: English

Description: A magical tale of witches and wizards

Book: The Witch's Curse

Genre: English

Description: A magical tale of wizards and witches

Book: The Witch's Curse

Genre: English

Description: A magical tale of wizards and witches

Book: The Witch's Curse

Genre: English

Description: A magical tale of wizards and witches

Book: The Witch's Curse

Genre: English

Description: A magical tale of wizards and witches

Book: The Witch's Curse

In [21]:
def ask_sherlock(query):

    query_vector = model.encode([query])
    distances, indices = index.search(np.array(query_vector), 3)

    results = df.iloc[indices[0]]

    response = f"\n  Query: {query}\n\n Recommended Books:\n"

    for _, row in results.iterrows():

        response += f"""
Title: {row['title']}
Genre: {row['genre']}
Description: {row['description']}

Why recommended:
This book matches your interest in "{query}" because it involves {row['description']} and belongs to the {row['genre']} genre.

"""

    return response

In [22]:
print(ask_sherlock("dark fantasy magic"))

  Query: dark fantasy magic

 Recommended Books:

Title: Harry Potter
Genre: Fantasy
Description: A young wizard discovering magic

Why recommended:
This book matches your interest in "dark fantasy magic" because it involves A young wizard discovering magic and belongs to the Fantasy genre.


Title: The Night Circus
Genre: Fantasy
Description: A magical competition between illusionists

Why recommended:
This book matches your interest in "dark fantasy magic" because it involves A magical competition between illusionists and belongs to the Fantasy genre.


Title: The Poppy War
Genre: Fantasy
Description: War and magic story with a powerful heroine

Why recommended:
This book matches your interest in "dark fantasy magic" because it involves War and magic story with a powerful heroine and belongs to the Fantasy genre.